handler: amc23
dataset_path: /cpfs/user/long2short/data/aimo-validation-amc
dataset_kwargs:
  trust_remote_code: true
dataset_split: train
question_key: problem
answer_key: answer
# Optionally, you can filter the dataset by difficulty
# preprocess_config:
#   difficulty: easy
templating_parameters: 
  template: "Return your final response within \\boxed{{}}. {problem}"
